namespace: wazuh-agent

image:
  repository: wazuh/wazuh-agent
  tag: "4.13.1"
  pullPolicy: IfNotPresent

manager:
  host: "your-managers-ip"
  port: 1514

securityContext:
  runAsUser: 0
  privileged: true

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
